### ISSUE TITLE
End of project checklist

### ISSUE THREAD

**Issue by ccharp** [ccharp/dplyPY#14]
This should be the last issue we resolve. Ensure the following have been addressed:
- all TODOs resolved
- all tests pass
- code properly documented (mostly referring to API documentation)

**Comment by ccharp** [comment]
@MatthewChau99 @nickjsr below is the official rubric for the software.

    README.md file that gives an overview of the project
    LICENSE file
    setup.py file that initializes the project after it has been cloned
    doc folder that contains documentation (including the functional specification, the design specification, and the final project presentation or poster)
    python package folder (with the same name as the repository) that is structured as one or more python modules (e.g., with init.py files) and test files that begin with “test_”.
    examples folder that contains examples of using the packages

Software Rubric

Projects will be evaluated based on the following criteria:

    Organized as described in the section on project structure
    Quality of the documentation (especially the functional specification and design specification)
    Code quality, especially consistent coding standard (e.g., `flake8`).
    Test coverage
    Quality of the example of using the package (in the examples folder of the project repository)
    Implements continuous integration (e.g., via travis-CI), and all tests pass.
    Completeness of the setup.py script
    Creativity and technical challenge
    PDF of your presentation and written report in the docs folder of your project

**Comment by nickjsr** [comment]
Thanks Corbin!

**Comment by nickjsr** [comment]
I created a google doc for documentation on functional specification and the design specification. 
The link is https://docs.google.com/document/d/1TMQDz056_rTYxK9tnxopQ4px4kkeRZ0s0vYKtnRsxp8/edit?usp=sharing

**Comment by nickjsr** [comment]
I have merged the last branch. I think we are done. Good job!
