### ISSUE TITLE
src __getitem__ bug

### ISSUE THREAD

**Issue by nickjsr** [ccharp/dplyPY#23]
Found a potential bug of __getitem__ when I implemented check_null on indexing a column of a dataframe. Details in https://github.com/ccharp/dplyPY/issues/9. In short, our __getitem__ treats dataframe[column name] as dataframe[index of column name].

**Comment by nickjsr** [comment]
I think of a way to bypass this bug: in src dplypy.py __init__, we have self.pandas_df, at the same place storing column names may be a good idea.  I am not sure if it is a good practice.

**Comment by ccharp** [comment]
Looking into this...

**Comment by nickjsr** [comment]
Update: adding pandas_df.columns is not needed. There was a bug in my pipeline. Now we have fixed it

**Comment by ccharp** [comment]
@nickjsr if I'm understanding correctly, this bug does not exist? I need to write tests for __get_item__() anyway, but you can close this of the issue is resolved. I'm signing off for the night

**Comment by nickjsr** [comment]
We can test getitem later
