### ISSUE TITLE
add tests for new functions in dplypy.py

### ISSUE THREAD

**Issue by nickjsr** [ccharp/dplyPY#36]
\__setitem\__, 
\__eq\__, 
\__lt\__, 
\__le\__, 
\__gt\__, 
\__ge\__, 
\__ne\__, 
deepcopy,
arrange

**Comment by ccharp** [comment]
tests for _eq_,
_lt_,
_le_,
_gt_,
_ge_,
_ne_,

have been added

**Comment by nickjsr** [comment]
All above tests have been covered. See pull request #47
