### ISSUE TITLE
select function does not accept using "+" and "!=" together

### ISSUE THREAD

**Issue by nickjsr** [ccharp/dplyPY#38]
I see you added \__ne\__, but currently when I try to test "df2 + select("col2+col3 != 1")," maximum recursion iteration reached. Is it a bug or intended? Thanks!

**Comment by ccharp** [comment]
Please verify on your end and close

**Comment by MatthewChau99** [comment]
When I tested with the titanic dataframe, I don't get any errors. I was using `output_9 = test_df_1 + select("survived + pclass != 4")`, where test_df_1 is the titanic dataframe.

**Comment by nickjsr** [comment]
Thank you everyone, maybe due to the digits in column names. Stick with Matthew's test for titanic. Thanks
