### ISSUE TITLE
Polish README

### ISSUE THREAD

**Issue by nickjsr** [ccharp/dplyPY#54]
Shared doc link: https://docs.google.com/document/d/1TMQDz056_rTYxK9tnxopQ4px4kkeRZ0s0vYKtnRsxp8/edit
I believe we need:
1. project organization tree
2. one sentence referring usage to example folder, and pipeline methods explanation with moderate details
3. one sentence explaining GitHub action building pass instead of travis-CI
4. one sentence mentioning using pylint instead of flake8 to check style
5. one sample output in the end extracted from examples.ipynb

**Comment by nickjsr** [comment]
I have given my inputs. Please take a look. Remember to add a project organization tree. Thanks!

**Comment by ccharp** [comment]
Thought: I don't think we need to enumerate the entire pipeline API. I simply suggested the reader look at pipeline.py to see the full API. We also have the docstrings that'll be packaged up and read by their IDE. 

What do you think, @nickjsr ?

**Comment by nickjsr** [comment]
> Thought: I don't think we need to enumerate the entire pipeline API. I simply suggested the reader look at pipeline.py to see the full API. We also have the docstrings that'll be packaged up and read by their IDE.
> 
> What do you think, @nickjsr ?

@ccharp Thanks for your suggestion. I think we need to enumerate the entire pipeline API somewhere. One reason is that there is no usage instruction in examples.ipynb

**Comment by ccharp** [comment]
@nickjsr my latest push to readme-updates includes API documentation generated from the doc strings in the code. The readme now has a link to that documentation. I think it should all work when merged.

**Comment by nickjsr** [comment]
> @nickjsr my latest push to readme-updates includes API documentation generated from the doc strings in the code. The readme now has a link to that documentation. I think it should all work when merged.

Thank you very much Corbin. Well done
