### ISSUE TITLE
Implement pipeline.check_null(), pipeline.dropna(), pipeline.fillna()

### ISSUE THREAD

**Issue by ccharp** [ccharp/dplyPY#9]
@nickjsr What does this do?

**Comment by nickjsr** [comment]
I assigned myself just now. It can check the number of null values in a dataframe or a series in a dataframe, checks if there is any null value in a dataframe or a series in a dataframe, and checks all entries of dataframe or a series in a dataframe if they are null respectively.

**Comment by nickjsr** [comment]
Update: I think checking if all entries are null respectively is not aesthetically appealing, especially for the whole dataframe. Also, it is not as useful as the other two types, so I just implement check if any and check total sum of missing values

**Comment by nickjsr** [comment]
Update: It works well for dataframe checking, but fails at column-wise.
I look into the error and find that __getitem__() inside src returns the index of the dataframe columns, e.g.. [0,1,2], but I use df[column], e.g. ["col1", "col2", "col3"], to get the desired series.
The error message is here:
<img width="638" alt="ErrorGetItem" src="https://user-images.githubusercontent.com/35482654/155292550-ec6cbe4c-06c4-4479-bc99-39a24d835519.png">

**Comment by nickjsr** [comment]
Link to my added code for pipeline.py: https://github.com/ccharp/dplyPY/blob/check_null/src/pipeline.py

**Comment by nickjsr** [comment]
Description based on the image: I need self.pandas_df[item]. Here "item" is the column name. Then it goes to self.columns.get_loc(key), which returns the numerical index of "item," which is not desired

**Comment by MatthewChau99** [comment]
Hmm if I change `if ((column is None) or (column in d1))` to `if ((column is None) or (column in d1.pandas_df))` it worked...

**Comment by nickjsr** [comment]
Yes, Matthew you are correct

**Comment by nickjsr** [comment]
I include dropna and fillna here, which are more useful and similar

**Comment by nickjsr** [comment]
I deleted check_null_any, renamed check_null_total to count_null, and deleted manual error handlinng
